redeemable_item_message: "&d&l★ You have redeemed this <redeem_name>!"
unredeemable_item_message: "&4&l☠ This item is not redeemable..."
redeemable_item_error: "&4&l☠ An error occurred while redeeming this item! You have been refunded."